# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Proyeccion_produccion(object):
    def setupUi(self, Proyeccion_produccion):
        Proyeccion_produccion.setObjectName("Proyeccion_produccion")
        Proyeccion_produccion.resize(875, 489)
        self.fechaDesde = QtWidgets.QDateEdit(Proyeccion_produccion)
        self.fechaDesde.setGeometry(QtCore.QRect(80, 120, 110, 22))
        self.fechaDesde.setObjectName("fechaDesde")
        self.fechahasta = QtWidgets.QDateEdit(Proyeccion_produccion)
        self.fechahasta.setGeometry(QtCore.QRect(280, 120, 110, 22))
        self.fechahasta.setObjectName("fechahasta")
        self.label = QtWidgets.QLabel(Proyeccion_produccion)
        self.label.setGeometry(QtCore.QRect(20, 120, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Proyeccion_produccion)
        self.label_2.setGeometry(QtCore.QRect(210, 120, 58, 16))
        self.label_2.setObjectName("label_2")
        self.btn_buscar = QtWidgets.QPushButton(Proyeccion_produccion)
        self.btn_buscar.setGeometry(QtCore.QRect(590, 110, 141, 32))
        self.btn_buscar.setObjectName("btn_buscar")
        self.titulo_ventas_historicas = QtWidgets.QLabel(Proyeccion_produccion)
        self.titulo_ventas_historicas.setGeometry(QtCore.QRect(20, 70, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.titulo_ventas_historicas.setFont(font)
        self.titulo_ventas_historicas.setObjectName("titulo_ventas_historicas")
        self.btn_descargar = QtWidgets.QPushButton(Proyeccion_produccion)
        self.btn_descargar.setGeometry(QtCore.QRect(590, 170, 141, 32))
        self.btn_descargar.setObjectName("btn_descargar")
        self.etiqueta = QtWidgets.QLabel(Proyeccion_produccion)
        self.etiqueta.setGeometry(QtCore.QRect(20, 210, 831, 21))
        self.etiqueta.setText("")
        self.etiqueta.setObjectName("etiqueta")
        self.label_mensaje_request = QtWidgets.QLabel(Proyeccion_produccion)
        self.label_mensaje_request.setGeometry(QtCore.QRect(20, 230, 831, 101))
        self.label_mensaje_request.setText("")
        self.label_mensaje_request.setObjectName("label_mensaje_request")

        self.retranslateUi(Proyeccion_produccion)
        QtCore.QMetaObject.connectSlotsByName(Proyeccion_produccion)

    def retranslateUi(self, Proyeccion_produccion):
        _translate = QtCore.QCoreApplication.translate
        Proyeccion_produccion.setWindowTitle(_translate("Proyeccion_produccion", "Proyeccion de producción"))
        self.fechaDesde.setDisplayFormat(_translate("Proyeccion_produccion", "dd/MM/yy"))
        self.fechahasta.setDisplayFormat(_translate("Proyeccion_produccion", "dd/MM/yy"))
        self.label.setText(_translate("Proyeccion_produccion", "Desde"))
        self.label_2.setText(_translate("Proyeccion_produccion", "Hasta"))
        self.btn_buscar.setText(_translate("Proyeccion_produccion", "Buscar"))
        self.titulo_ventas_historicas.setText(_translate("Proyeccion_produccion", "Ventas Historicas"))
        self.btn_descargar.setText(_translate("Proyeccion_produccion", "Abrir excel"))
